'use client';

import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { BadgeIndianRupee, CheckCircle2, FileCheck2, ReceiptIndianRupee, RefreshCw, ShieldAlert, Upload, WalletCards, XCircle } from 'lucide-react';
import { getSupabaseNetworkClient } from '@/lib/supabase-network-client';
import { summarizeCommissionLedger, type CommissionLedgerEntry } from '@/lib/commission-ledger';

const inputClass='w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const primaryButton='inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50';
const secondaryButton='inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50';
const dangerButton='inline-flex items-center justify-center gap-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-100 disabled:opacity-50';
const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(value||0);

type Profile={id:string;broker_code:string;display_name:string;firm:string;is_admin:boolean};
type Deal={id:string;buyer_user_id:string;listing_user_id:string;status:string;last_offer:number|null;property_id:string;requirement_id:string};
type Agreement={id:string;deal_id:string;version:number;status:string;method:'fixed'|'percentage';fixed_amount:number|null;percentage:number|null};
type Allocation={agreement_id:string;deal_id:string;broker_user_id:string;role:string;share_percent:number};
type Closing={id:string;deal_id:string;agreement_id:string;version:number;final_price:number;status:string;proof_type:string;proof_reference:string;proposed_by_user_id:string;confirmed_at:string|null;created_at:string};
type ClosingAcceptance={closing_id:string;user_id:string;decision:string;note:string};
type Ledger={id:string;deal_id:string;agreement_id:string|null;broker_user_id:string;entry_type:CommissionLedgerEntry['entry_type'];amount:number;status:CommissionLedgerEntry['status'];reference:string|null;note:string;created_at:string};
type ClosingDocument={id:string;deal_id:string;closing_id:string;document_type:string;storage_bucket:string;storage_path:string;original_name:string;mime_type:string;size_bytes:number;uploaded_by_user_id:string;created_at:string};
type Dispute={id:string;deal_id:string;agreement_id:string|null;raised_by_user_id:string;against_user_id:string|null;amount_disputed:number|null;reason:string;status:string;resolution:string;created_at:string};
type BuilderProject={id:string;builder_id:string;name:string;city:string;locality:string|null;brokerage_pct:number;status:string};
type BuilderPayout={id:string;deal_id:string;project_id:string;broker_user_id:string;amount:number;status:string;reference:string;note:string;paid_at:string|null;updated_at:string};

function profileLabel(profiles:Profile[],id:string){const p=profiles.find(x=>x.id===id);return p?`${p.display_name} · ${p.broker_code}`:id.slice(0,8);}
function safeFileName(name:string){return name.replace(/[^a-zA-Z0-9._-]+/g,'-').slice(-120)||'proof';}

export default function CommissionOperations(){
 const supabase=useMemo(()=>getSupabaseNetworkClient(),[]);
 const [userId,setUserId]=useState('');
 const [isAdmin,setIsAdmin]=useState(false);
 const [profiles,setProfiles]=useState<Profile[]>([]),[deals,setDeals]=useState<Deal[]>([]),[agreements,setAgreements]=useState<Agreement[]>([]),[allocations,setAllocations]=useState<Allocation[]>([]),[closings,setClosings]=useState<Closing[]>([]),[closingAcceptances,setClosingAcceptances]=useState<ClosingAcceptance[]>([]),[ledger,setLedger]=useState<Ledger[]>([]),[documents,setDocuments]=useState<ClosingDocument[]>([]),[disputes,setDisputes]=useState<Dispute[]>([]),[projects,setProjects]=useState<BuilderProject[]>([]),[payouts,setPayouts]=useState<BuilderPayout[]>([]);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [closingForm,setClosingForm]=useState({dealId:'',finalPrice:'',proofType:'agreement',proofReference:''});
 const [activityForm,setActivityForm]=useState({dealId:'',entryType:'invoice',amount:'',reference:'',note:''});
 const [proofForm,setProofForm]=useState({closingId:'',documentType:'agreement'});
 const [proofFile,setProofFile]=useState<File|null>(null);
 const [payoutForm,setPayoutForm]=useState({dealId:'',projectId:'',brokerUserId:'',amount:'',status:'expected',reference:'',note:''});

 const load=useCallback(async()=>{
  setMessage('');
  const auth=await supabase.auth.getUser(); if(auth.error)throw auth.error;
  const uid=auth.data.user?.id||''; setUserId(uid); if(!uid)return;
  const profileRes=await supabase.from('genz_profiles').select('id,broker_code,display_name,firm,is_admin').eq('id',uid).maybeSingle();
  if(profileRes.error)throw profileRes.error; setIsAdmin(Boolean(profileRes.data?.is_admin));
  const results=await Promise.all([
   supabase.from('genz_profiles').select('id,broker_code,display_name,firm,is_admin').order('display_name'),
   supabase.from('genz_deals').select('id,buyer_user_id,listing_user_id,status,last_offer,property_id,requirement_id').order('created_at',{ascending:false}),
   supabase.from('genz_commission_agreements').select('id,deal_id,version,status,method,fixed_amount,percentage').order('version',{ascending:false}),
   supabase.from('genz_commission_allocations').select('agreement_id,deal_id,broker_user_id,role,share_percent'),
   supabase.from('genz_deal_closings').select('*').order('created_at',{ascending:false}),
   supabase.from('genz_deal_closing_acceptances').select('closing_id,user_id,decision,note'),
   supabase.from('genz_commission_ledger').select('*').order('created_at',{ascending:false}),
   supabase.from('genz_closing_documents').select('*').order('created_at',{ascending:false}),
   supabase.from('genz_commission_disputes').select('*').order('created_at',{ascending:false}),
   supabase.from('genz_builder_projects').select('id,builder_id,name,city,locality,brokerage_pct,status').eq('status','active').order('name'),
   supabase.from('genz_builder_payouts').select('*').order('updated_at',{ascending:false}),
  ]);
  for(const r of results)if(r.error)throw r.error;
  const ps=(results[0].data||[]) as Profile[],ds=(results[1].data||[]) as Deal[];
  setProfiles(ps);setDeals(ds);setAgreements((results[2].data||[]) as Agreement[]);setAllocations((results[3].data||[]) as Allocation[]);setClosings((results[4].data||[]) as Closing[]);setClosingAcceptances((results[5].data||[]) as ClosingAcceptance[]);setLedger((results[6].data||[]) as Ledger[]);setDocuments((results[7].data||[]) as ClosingDocument[]);setDisputes((results[8].data||[]) as Dispute[]);setProjects((results[9].data||[]) as BuilderProject[]);setPayouts((results[10].data||[]) as BuilderPayout[]);
  const firstDeal=ds[0]?.id||'';
  setClosingForm(v=>({...v,dealId:v.dealId||firstDeal})); setActivityForm(v=>({...v,dealId:v.dealId||firstDeal})); setPayoutForm(v=>({...v,dealId:v.dealId||firstDeal}));
 },[supabase]);
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:'Could not load Phase 2.3 operations.'));},[load]);

 const myLedger=useMemo(()=>ledger.filter(x=>x.broker_user_id===userId),[ledger,userId]);
 const earnings=useMemo(()=>summarizeCommissionLedger(myLedger),[myLedger]);
 const acceptedAgreement=(dealId:string)=>agreements.find(a=>a.deal_id===dealId&&a.status==='accepted');
 const allocatedBrokers=(dealId:string)=>{const a=acceptedAgreement(dealId);return a?allocations.filter(x=>x.agreement_id===a.id):[];};

 async function proposeClosing(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const price=Number(closingForm.finalPrice);if(!closingForm.dealId||!price)throw new Error('Choose a deal and enter final selling price.');const {error}=await supabase.rpc('genz_propose_deal_closing',{p_deal_id:closingForm.dealId,p_final_price:price,p_proof_type:closingForm.proofType,p_proof_reference:closingForm.proofReference});if(error)throw error;setClosingForm(v=>({...v,finalPrice:'',proofReference:''}));setMessage('Closing proposed. The other deal broker must confirm the same final price.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not propose closing.');}finally{setBusy(false);}}
 async function respondClosing(id:string,accept:boolean){setBusy(true);setMessage('');try{const {data,error}=await supabase.rpc('genz_respond_deal_closing',{p_closing_id:id,p_accept:accept,p_note:accept?'Confirmed final selling price':'Closing details rejected; revised closing required'});if(error)throw error;setMessage(`Closing is now ${String(data||'updated')}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not respond to closing.');}finally{setBusy(false);}}
 async function recordActivity(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const amount=Number(activityForm.amount);if(!amount)throw new Error('Enter an amount.');const {error}=await supabase.rpc('genz_record_commission_activity',{p_deal_id:activityForm.dealId,p_entry_type:activityForm.entryType,p_amount:amount,p_reference:activityForm.reference,p_note:activityForm.note,p_broker_user_id:null});if(error)throw error;setActivityForm(v=>({...v,amount:'',reference:'',note:''}));setMessage(`${activityForm.entryType} recorded and queued for verification.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not record commission activity.');}finally{setBusy(false);}}
 async function reviewLedger(id:string,status:'confirmed'|'disputed'|'void'){const note=window.prompt(`Admin note for ${status}:`,'')||'';setBusy(true);setMessage('');try{const {error}=await supabase.rpc('genz_admin_review_commission_entry',{p_entry_id:id,p_status:status,p_note:note});if(error)throw error;setMessage(`Ledger entry marked ${status}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not review ledger entry.');}finally{setBusy(false);}}
 async function resolveDispute(id:string,status:'evidence_requested'|'resolved'|'rejected'){const resolution=window.prompt(status==='evidence_requested'?'What evidence is required?':'Enter resolution note:','')||'';if(!resolution)return;setBusy(true);setMessage('');try{const {error}=await supabase.rpc('genz_admin_resolve_commission_dispute',{p_dispute_id:id,p_status:status,p_resolution:resolution});if(error)throw error;setMessage(`Dispute marked ${status.replace('_',' ')}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not resolve dispute.');}finally{setBusy(false);}}
 async function saveBuilderPayout(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const amount=Number(payoutForm.amount);if(!payoutForm.projectId||!payoutForm.brokerUserId||!amount)throw new Error('Choose project, broker and amount.');const {error}=await supabase.rpc('genz_upsert_builder_payout',{p_deal_id:payoutForm.dealId,p_project_id:payoutForm.projectId,p_broker_user_id:payoutForm.brokerUserId,p_amount:amount,p_status:payoutForm.status,p_reference:payoutForm.reference,p_note:payoutForm.note});if(error)throw error;setPayoutForm(v=>({...v,amount:'',reference:'',note:''}));setMessage(`Builder payout saved as ${payoutForm.status}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not save builder payout.');}finally{setBusy(false);}}
 async function uploadProof(event:FormEvent){event.preventDefault();if(!proofFile||!proofForm.closingId)return setMessage('Choose a closing and proof file.');if(proofFile.size>10485760)return setMessage('Proof file must be 10 MB or smaller.');if(!['application/pdf','image/jpeg','image/png'].includes(proofFile.type))return setMessage('Upload PDF, JPG or PNG only.');const closing=closings.find(x=>x.id===proofForm.closingId);if(!closing)return;setBusy(true);setMessage('');const path=`${userId}/closing/${closing.deal_id}/${crypto.randomUUID()}-${safeFileName(proofFile.name)}`;try{const upload=await supabase.storage.from('genz-property-docs').upload(path,proofFile,{contentType:proofFile.type,upsert:false});if(upload.error)throw upload.error;const {error}=await supabase.rpc('genz_register_closing_document',{p_closing_id:closing.id,p_storage_path:path,p_document_type:proofForm.documentType,p_original_name:proofFile.name,p_mime_type:proofFile.type,p_size_bytes:proofFile.size});if(error){await supabase.storage.from('genz-property-docs').remove([path]);throw error;}setProofFile(null);setMessage('Closing proof uploaded and linked to the deal audit trail.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not upload proof.');}finally{setBusy(false);}}
 async function openDocument(doc:ClosingDocument){setMessage('');const {data,error}=await supabase.storage.from(doc.storage_bucket).createSignedUrl(doc.storage_path,300);if(error){setMessage(error.message);return;}window.open(data.signedUrl,'_blank','noopener,noreferrer');}

 return <section className="space-y-7 border-t border-slate-200 pt-8">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Phase 2.3 · Operations</div><h2 className="mt-1 text-2xl font-bold tracking-tight">Closing, earnings & payout controls</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">A confirmed closing converts the accepted commission split into earned broker entitlements. Invoices, payments and refunds are evidence records; GENZ does not hold money.</p></div><button className={secondaryButton} onClick={()=>void load()}><RefreshCw className="size-4"/>Refresh</button></div>
  {message&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900">{message}</div>}

  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
   {[['Earned',earnings.earned],['Confirmed paid',earnings.paymentsConfirmed],['Pending payment proof',earnings.paymentsPending],['Outstanding',earnings.outstanding]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold text-slate-950">{money(Number(value))}</div></div>)}
  </div>

  <div className="grid gap-5 xl:grid-cols-2">
   <form onSubmit={proposeClosing} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><FileCheck2 className="size-5 text-blue-600"/><h3 className="font-bold">Confirm final deal closing</h3></div><p className="mt-1 text-xs leading-5 text-slate-500">Requires an accepted commission agreement. The other deal broker must confirm before entitlements are earned.</p><div className="mt-4 grid gap-3"><select className={inputClass} value={closingForm.dealId} onChange={e=>setClosingForm({...closingForm,dealId:e.target.value})}><option value="">Select deal</option>{deals.filter(d=>d.status!=='closed'&&acceptedAgreement(d.id)).map(d=><option key={d.id} value={d.id}>{d.id} · {d.status}</option>)}</select><input className={inputClass} type="number" min="1" step="0.01" placeholder="Final selling price ₹" value={closingForm.finalPrice} onChange={e=>setClosingForm({...closingForm,finalPrice:e.target.value})}/><select className={inputClass} value={closingForm.proofType} onChange={e=>setClosingForm({...closingForm,proofType:e.target.value})}><option value="booking">Booking</option><option value="agreement">Agreement</option><option value="registry">Registry</option><option value="builder_booking">Builder booking</option><option value="other">Other</option></select><input className={inputClass} placeholder="Proof/reference note (optional)" maxLength={500} value={closingForm.proofReference} onChange={e=>setClosingForm({...closingForm,proofReference:e.target.value})}/><button disabled={busy||!closingForm.dealId} className={primaryButton}><CheckCircle2 className="size-4"/>Propose closing</button></div></form>

   <form onSubmit={recordActivity} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ReceiptIndianRupee className="size-5 text-blue-600"/><h3 className="font-bold">Record invoice / payment</h3></div><p className="mt-1 text-xs leading-5 text-slate-500">Manual payment records stay pending until reviewed. They cannot exceed your earned entitlement.</p><div className="mt-4 grid gap-3"><select className={inputClass} value={activityForm.dealId} onChange={e=>setActivityForm({...activityForm,dealId:e.target.value})}><option value="">Select closed deal</option>{deals.filter(d=>d.status==='closed').map(d=><option key={d.id} value={d.id}>{d.id}</option>)}</select><select className={inputClass} value={activityForm.entryType} onChange={e=>setActivityForm({...activityForm,entryType:e.target.value})}><option value="invoice">Invoice issued</option><option value="payment">Payment received</option><option value="refund">Refund / reversal</option></select><input className={inputClass} type="number" min="0.01" step="0.01" placeholder="Amount ₹" value={activityForm.amount} onChange={e=>setActivityForm({...activityForm,amount:e.target.value})}/><input className={inputClass} maxLength={500} placeholder="Invoice/UTR/reference" value={activityForm.reference} onChange={e=>setActivityForm({...activityForm,reference:e.target.value})}/><textarea className={inputClass} maxLength={1200} placeholder="Note" value={activityForm.note} onChange={e=>setActivityForm({...activityForm,note:e.target.value})}/><button disabled={busy||!activityForm.dealId} className={primaryButton}><BadgeIndianRupee className="size-4"/>Record activity</button></div></form>
  </div>

  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><WalletCards className="size-5 text-blue-600"/><h3 className="font-bold">Closing confirmations</h3></div><div className="mt-4 grid gap-3">{closings.map(c=>{const deal=deals.find(d=>d.id===c.deal_id);const mine=closingAcceptances.find(a=>a.closing_id===c.id&&a.user_id===userId);const canRespond=c.status==='proposed'&&deal&&[deal.buyer_user_id,deal.listing_user_id].includes(userId)&&mine?.decision!=='accepted';return <article key={c.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><b>{c.deal_id} · Closing v{c.version}</b><div className="mt-1 text-sm text-slate-700">Final price {money(Number(c.final_price))}</div><div className="mt-1 text-xs text-slate-500">{c.proof_type.replace('_',' ')}{c.proof_reference?` · ${c.proof_reference}`:''}</div></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${c.status==='confirmed'?'bg-emerald-50 text-emerald-700':c.status==='rejected'?'bg-red-50 text-red-700':'bg-blue-50 text-blue-700'}`}>{c.status}</span></div>{canRespond&&<div className="mt-3 flex gap-2"><button disabled={busy} className={primaryButton} onClick={()=>void respondClosing(c.id,true)}><CheckCircle2 className="size-4"/>Confirm</button><button disabled={busy} className={dangerButton} onClick={()=>void respondClosing(c.id,false)}><XCircle className="size-4"/>Reject</button></div>}</article>;})}{!closings.length&&<div className="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No closing proposals yet.</div>}</div></section>

  <div className="grid gap-5 xl:grid-cols-2">
   <form onSubmit={uploadProof} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Upload className="size-5 text-blue-600"/><h3 className="font-bold">Closing proof documents</h3></div><div className="mt-4 grid gap-3"><select className={inputClass} value={proofForm.closingId} onChange={e=>setProofForm({...proofForm,closingId:e.target.value})}><option value="">Select closing</option>{closings.filter(c=>c.status!=='rejected').map(c=><option key={c.id} value={c.id}>{c.deal_id} · v{c.version} · {c.status}</option>)}</select><select className={inputClass} value={proofForm.documentType} onChange={e=>setProofForm({...proofForm,documentType:e.target.value})}><option value="agreement">Agreement</option><option value="booking">Booking</option><option value="registry">Registry</option><option value="builder_booking">Builder booking</option><option value="invoice">Invoice</option><option value="payment_proof">Payment proof</option><option value="other">Other</option></select><input className={inputClass} type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>setProofFile(e.target.files?.[0]||null)}/><button disabled={busy||!proofFile||!proofForm.closingId} className={primaryButton}><Upload className="size-4"/>Upload proof</button></div><div className="mt-4 space-y-2">{documents.slice(0,8).map(d=><button type="button" key={d.id} className="flex w-full items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-left text-xs hover:bg-slate-50" onClick={()=>void openDocument(d)}><span><b>{d.original_name}</b><br/><span className="text-slate-500">{d.deal_id} · {d.document_type}</span></span><span className="text-blue-600">Open</span></button>)}</div></form>

   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">My earnings ledger</h3><div className="mt-4 space-y-2">{myLedger.slice(0,12).map(e=><div key={e.id} className="flex items-start justify-between gap-3 rounded-lg border border-slate-200 p-3"><div><b className="text-sm">{e.entry_type} · {money(Number(e.amount))}</b><div className="mt-1 text-xs text-slate-500">{e.deal_id}{e.reference?` · ${e.reference}`:''}</div></div><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${e.status==='confirmed'?'bg-emerald-50 text-emerald-700':e.status==='disputed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{e.status}</span></div>)}{!myLedger.length&&<div className="text-sm text-slate-500">No earnings entries yet.</div>}</div></section>
  </div>

  {payouts.length>0&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Builder payout tracking</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{payouts.map(p=><div key={p.id} className="rounded-xl border border-slate-200 p-4"><b>{money(Number(p.amount))} · {p.status}</b><div className="mt-1 text-xs text-slate-500">{p.deal_id} · {projects.find(x=>x.id===p.project_id)?.name||'Builder project'} · {profileLabel(profiles,p.broker_user_id)}</div>{p.reference&&<div className="mt-2 text-xs text-slate-600">{p.reference}</div>}</div>)}</div></section>}

  {isAdmin&&<div className="grid gap-5 xl:grid-cols-2">
   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldAlert className="size-5 text-amber-600"/><h3 className="font-bold">Admin verification queue</h3></div><div className="mt-4 space-y-3">{ledger.filter(e=>['invoice','payment','refund'].includes(e.entry_type)&&e.status==='pending').map(e=><div key={e.id} className="rounded-xl border border-slate-200 p-3"><b className="text-sm">{e.entry_type} · {money(Number(e.amount))}</b><div className="mt-1 text-xs text-slate-500">{e.deal_id} · {profileLabel(profiles,e.broker_user_id)}{e.reference?` · ${e.reference}`:''}</div><div className="mt-3 flex flex-wrap gap-2"><button className={secondaryButton} disabled={busy} onClick={()=>void reviewLedger(e.id,'confirmed')}>Confirm</button><button className={secondaryButton} disabled={busy} onClick={()=>void reviewLedger(e.id,'disputed')}>Dispute</button><button className={dangerButton} disabled={busy} onClick={()=>void reviewLedger(e.id,'void')}>Void</button></div></div>)}{!ledger.some(e=>['invoice','payment','refund'].includes(e.entry_type)&&e.status==='pending')&&<div className="text-sm text-slate-500">No pending ledger evidence.</div>}</div></section>

   <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Admin dispute desk</h3><div className="mt-4 space-y-3">{disputes.filter(d=>!['resolved','rejected'].includes(d.status)).map(d=><div key={d.id} className="rounded-xl border border-slate-200 p-3"><b className="text-sm">{d.deal_id} · {d.status.replace('_',' ')}</b><div className="mt-1 text-xs leading-5 text-slate-600">{d.reason}</div>{d.amount_disputed!==null&&<div className="mt-1 text-xs font-semibold">Disputed: {money(Number(d.amount_disputed))}</div>}<div className="mt-3 flex flex-wrap gap-2"><button className={secondaryButton} disabled={busy} onClick={()=>void resolveDispute(d.id,'evidence_requested')}>Request evidence</button><button className={secondaryButton} disabled={busy} onClick={()=>void resolveDispute(d.id,'resolved')}>Resolve</button><button className={dangerButton} disabled={busy} onClick={()=>void resolveDispute(d.id,'rejected')}>Reject</button></div></div>)}{!disputes.some(d=>!['resolved','rejected'].includes(d.status))&&<div className="text-sm text-slate-500">No open commission disputes.</div>}</div></section>

   <form onSubmit={saveBuilderPayout} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><h3 className="font-bold">Builder payout linkage</h3><p className="mt-1 text-xs text-slate-500">Admin can link a builder project payout to an earned broker entitlement. Marking it paid creates an idempotent confirmed payment ledger entry.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select className={inputClass} value={payoutForm.dealId} onChange={e=>setPayoutForm({...payoutForm,dealId:e.target.value,brokerUserId:''})}><option value="">Select closed deal</option>{deals.filter(d=>d.status==='closed').map(d=><option key={d.id} value={d.id}>{d.id}</option>)}</select><select className={inputClass} value={payoutForm.projectId} onChange={e=>setPayoutForm({...payoutForm,projectId:e.target.value})}><option value="">Select builder project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.city}</option>)}</select><select className={inputClass} value={payoutForm.brokerUserId} onChange={e=>setPayoutForm({...payoutForm,brokerUserId:e.target.value})}><option value="">Select allocated broker</option>{allocatedBrokers(payoutForm.dealId).map(a=><option key={a.broker_user_id} value={a.broker_user_id}>{profileLabel(profiles,a.broker_user_id)} · {a.share_percent}%</option>)}</select><input className={inputClass} type="number" min="0.01" step="0.01" placeholder="Payout amount ₹" value={payoutForm.amount} onChange={e=>setPayoutForm({...payoutForm,amount:e.target.value})}/><select className={inputClass} value={payoutForm.status} onChange={e=>setPayoutForm({...payoutForm,status:e.target.value})}><option value="expected">Expected</option><option value="approved">Approved</option><option value="paid">Paid</option><option value="rejected">Rejected</option></select><input className={inputClass} maxLength={500} placeholder="Builder payout reference" value={payoutForm.reference} onChange={e=>setPayoutForm({...payoutForm,reference:e.target.value})}/><input className={inputClass} maxLength={1200} placeholder="Note" value={payoutForm.note} onChange={e=>setPayoutForm({...payoutForm,note:e.target.value})}/><button disabled={busy||!payoutForm.dealId} className={primaryButton}>Save builder payout</button></div></form>
  </div>}
 </section>;
}
