'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, BadgeCheck, CheckCircle2, Clock3, Network, RefreshCw, Search, ShieldCheck, Sparkles, UsersRound, XCircle } from 'lucide-react';
import { getSupabaseNetworkClient } from '@/lib/supabase-network-client';
import { calculateTrustScore } from '@/lib/trust-score';
import { rankPropertyMatches, scorePropertyMatch } from '@/lib/matching-v2';
import { daysUntilExpiry, opportunityMatchesQuery, rankBrokerRelevance } from '@/lib/opportunity-v2';

const inputClass='w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const primaryButton='inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:opacity-50';
const secondaryButton='inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50';
const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value||0);

type Profile={id:string;broker_code:string;display_name:string;firm:string;cities:string[];specialties:string[];verified:boolean;completed_deals:number;successful_collaborations:number;verified_visits:number;collaboration_requests:number;collaboration_responses:number;rating:number;review_count:number;unresolved_disputes:number;owner_confirmed_listings:number;is_admin:boolean};
type Requirement={id:string;source_user_id:string;buyer_label:string;buyer_phone_masked:string;city:string;property_type:string;max_budget:number;min_size:number;status:string;expires_at:string;created_at:string};
type Property={id:string;listing_user_id:string;title:string;city:string;locality:string|null;property_type:string;size:number;asking:number;mandate_status:string;status:string;created_at:string};
type Opportunity={id:string;source_type:'requirement'|'property';requirement_id:string|null;property_id:string|null;posted_by_user_id:string;audience:'network'|'selected'|'private';headline:string;note:string;status:'open'|'matched'|'paused'|'closed';expires_at:string|null;created_at:string;updated_at:string};
type Recipient={opportunity_id:string;broker_user_id:string};
type ResponseRow={id:string;opportunity_id:string;broker_user_id:string;response_type:'have_match'|'interested'|'pass';message:string;linked_requirement_id:string|null;linked_property_id:string|null;status:'active'|'accepted'|'rejected'|'withdrawn';created_at:string;updated_at:string};

function profileLabel(profiles:Profile[],id:string){const p=profiles.find(x=>x.id===id);return p?`${p.display_name} · ${p.firm}`:'GENZ broker';}
function demoBadge(id:string|null){return Boolean(id?.startsWith('DEMO-'));}

function OpportunitySettings({post,profiles,recipients,onSaved}:{post:Opportunity;profiles:Profile[];recipients:Recipient[];onSaved:()=>Promise<void>}){
 const supabase=useMemo(()=>getSupabaseNetworkClient(),[]);
 const [audience,setAudience]=useState<Opportunity['audience']>(post.audience);
 const [status,setStatus]=useState<Opportunity['status']>(post.status);
 const [headline,setHeadline]=useState(post.headline);
 const [note,setNote]=useState(post.note);
 const [selected,setSelected]=useState<string[]>(recipients.filter(r=>r.opportunity_id===post.id).map(r=>r.broker_user_id));
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(){setBusy(true);setMessage('');try{const {error}=await supabase.rpc('genz_configure_opportunity',{p_opportunity_id:post.id,p_audience:audience,p_headline:headline,p_note:note,p_status:status,p_expires_at:post.expires_at,p_recipient_ids:audience==='selected'?selected:[]});if(error)throw error;setMessage('Opportunity settings saved.');await onSaved();}catch(e){setMessage(e instanceof Error?e.message:'Could not save opportunity.');}finally{setBusy(false);}}
 return <details className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><summary className="cursor-pointer text-xs font-bold text-slate-700">Manage visibility & status</summary><div className="mt-3 grid gap-2"><select className={inputClass} value={audience} onChange={e=>setAudience(e.target.value as Opportunity['audience'])}><option value="network">Entire GENZ network</option><option value="selected">Selected brokers</option><option value="private">Private / owner only</option></select><select className={inputClass} value={status} onChange={e=>setStatus(e.target.value as Opportunity['status'])}><option value="open">Open</option><option value="matched">Matched</option><option value="paused">Paused</option><option value="closed">Closed</option></select><input className={inputClass} maxLength={180} value={headline} onChange={e=>setHeadline(e.target.value)}/><textarea className={inputClass} rows={3} maxLength={1200} value={note} onChange={e=>setNote(e.target.value)}/>{audience==='selected'&&<div className="rounded-lg border border-slate-200 bg-white p-3"><div className="text-xs font-bold text-slate-700">Selected brokers</div><div className="mt-2 grid gap-2">{profiles.filter(p=>p.id!==post.posted_by_user_id).map(p=><label key={p.id} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/>{p.display_name} · {p.firm}</label>)}</div></div>}<button className={secondaryButton} disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save opportunity'}</button>{message&&<div className="text-xs text-slate-600">{message}</div>}</div></details>;
}

function ResponseComposer({post,userId,requirements,properties,onSaved}:{post:Opportunity;userId:string;requirements:Requirement[];properties:Property[];onSaved:()=>Promise<void>}){
 const supabase=useMemo(()=>getSupabaseNetworkClient(),[]);
 const sources=post.source_type==='requirement'?properties.filter(p=>p.listing_user_id===userId&&p.status==='active'):requirements.filter(r=>r.source_user_id===userId&&r.status==='active');
 const [linked,setLinked]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 async function respond(type:'have_match'|'interested'|'pass'){setBusy(true);setNotice('');try{if(type==='have_match'&&!linked)throw new Error(post.source_type==='requirement'?'Select your matching property first.':'Select your matching buyer requirement first.');const {error}=await supabase.rpc('genz_respond_opportunity',{p_opportunity_id:post.id,p_response_type:type,p_message:message,p_linked_source_id:type==='have_match'?linked:null});if(error)throw error;setNotice(type==='have_match'?'Match sent to source broker.':type==='interested'?'Interest recorded.':'Marked not relevant.');await onSaved();}catch(e){setNotice(e instanceof Error?e.message:'Could not respond.');}finally{setBusy(false);}}
 return <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50/60 p-3"><div className="text-xs font-bold text-blue-900">Respond to this opportunity</div><div className="mt-2 grid gap-2"><select className={inputClass} value={linked} onChange={e=>setLinked(e.target.value)}><option value="">{post.source_type==='requirement'?'Select one of my properties':'Select one of my buyer requirements'}</option>{sources.map((s:any)=><option key={s.id} value={s.id}>{s.id} · {post.source_type==='requirement'?`${s.title} · ${s.city}`:`${s.property_type} · ${s.city}`}</option>)}</select><input className={inputClass} maxLength={1000} placeholder="Optional note to source broker" value={message} onChange={e=>setMessage(e.target.value)}/><div className="flex flex-wrap gap-2"><button className={primaryButton} disabled={busy} onClick={()=>void respond('have_match')}><ArrowRight className="size-4"/>{post.source_type==='requirement'?'I have matching property':'I have matching buyer'}</button><button className={secondaryButton} disabled={busy} onClick={()=>void respond('interested')}>Interested</button><button className={secondaryButton} disabled={busy} onClick={()=>void respond('pass')}>Not relevant</button></div>{notice&&<div className="text-xs text-blue-900">{notice}</div>}</div></div>;
}

export default function OpportunityNetwork(){
 const supabase=useMemo(()=>getSupabaseNetworkClient(),[]);
 const [userId,setUserId]=useState('');const [isAdmin,setIsAdmin]=useState(false);
 const [profiles,setProfiles]=useState<Profile[]>([]),[requirements,setRequirements]=useState<Requirement[]>([]),[properties,setProperties]=useState<Property[]>([]),[posts,setPosts]=useState<Opportunity[]>([]),[recipients,setRecipients]=useState<Recipient[]>([]),[responses,setResponses]=useState<ResponseRow[]>([]);
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[kind,setKind]=useState<'all'|'requirement'|'property'>('all'),[brokerCity,setBrokerCity]=useState(''),[brokerType,setBrokerType]=useState('');

 const load=useCallback(async()=>{setLoading(true);setMessage('');try{const auth=await supabase.auth.getUser();if(auth.error)throw auth.error;const uid=auth.data.user?.id||'';setUserId(uid);if(!uid)return;const results=await Promise.all([
  supabase.from('genz_profiles').select('id,broker_code,display_name,firm,cities,specialties,verified,completed_deals,successful_collaborations,verified_visits,collaboration_requests,collaboration_responses,rating,review_count,unresolved_disputes,owner_confirmed_listings,is_admin').order('display_name'),
  supabase.from('genz_requirements').select('id,source_user_id,buyer_label,buyer_phone_masked,city,property_type,max_budget,min_size,status,expires_at,created_at').order('created_at',{ascending:false}),
  supabase.from('genz_properties').select('id,listing_user_id,title,city,locality,property_type,size,asking,mandate_status,status,created_at').order('created_at',{ascending:false}),
  supabase.from('genz_opportunity_posts').select('*').order('created_at',{ascending:false}),
  supabase.from('genz_opportunity_recipients').select('opportunity_id,broker_user_id'),
  supabase.from('genz_opportunity_responses').select('*').order('updated_at',{ascending:false}),
 ]);for(const r of results)if(r.error)throw r.error;const ps=(results[0].data||[]) as Profile[];setProfiles(ps);setIsAdmin(Boolean(ps.find(p=>p.id===uid)?.is_admin));setRequirements((results[1].data||[]) as Requirement[]);setProperties((results[2].data||[]) as Property[]);setPosts((results[3].data||[]) as Opportunity[]);setRecipients((results[4].data||[]) as Recipient[]);setResponses((results[5].data||[]) as ResponseRow[]);}catch(e){setMessage(e instanceof Error?e.message:'Could not load opportunity exchange.');}finally{setLoading(false);}},[supabase]);
 useEffect(()=>{void load();const channel=supabase.channel('genz-opportunity-feed').on('postgres_changes',{event:'*',schema:'public',table:'genz_opportunity_posts'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'genz_opportunity_responses'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[load,supabase]);

 const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);
 const reqMap=useMemo(()=>new Map(requirements.map(r=>[r.id,r])),[requirements]);
 const propertyMap=useMemo(()=>new Map(properties.map(p=>[p.id,p])),[properties]);
 const filtered=useMemo(()=>posts.filter(post=>{if(kind!=='all'&&post.source_type!==kind)return false;const req=post.requirement_id?reqMap.get(post.requirement_id):undefined;const prop=post.property_id?propertyMap.get(post.property_id):undefined;const broker=profileMap.get(post.posted_by_user_id);return opportunityMatchesQuery({id:post.requirement_id||post.property_id||post.id,headline:post.headline,note:post.note,city:req?.city||prop?.city,locality:prop?.locality,propertyType:req?.property_type||prop?.property_type,brokerName:broker?.display_name,brokerFirm:broker?.firm},query);}),[posts,kind,query,reqMap,propertyMap,profileMap]);

 const brokerRankings=useMemo(()=>rankBrokerRelevance(profiles.map(p=>{const trust=calculateTrustScore({profileVerified:p.verified,ownerConfirmedListings:p.owner_confirmed_listings||0,completedDeals:p.completed_deals||0,successfulCollaborations:p.successful_collaborations||0,verifiedVisits:p.verified_visits||0,collaborationRequests:p.collaboration_requests||0,collaborationResponses:p.collaboration_responses||0,verifiedReviewAverage:Number(p.rating||0),verifiedReviewCount:p.review_count||0,unresolvedDisputes:p.unresolved_disputes||0});return{id:p.id,name:p.display_name,cities:p.cities||[],specialties:p.specialties||[],verified:p.verified,trustScore:trust.score};}),{city:brokerCity,propertyType:brokerType}),[profiles,brokerCity,brokerType]);

 async function acceptResponse(id:string){setMessage('');try{const {data,error}=await supabase.rpc('genz_accept_opportunity_response',{p_response_id:id});if(error)throw error;setMessage(`Match accepted. Deal room ${String(data||'created')} is ready.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not accept match.');}}
 async function rejectResponse(id:string){setMessage('');try{const {error}=await supabase.rpc('genz_review_opportunity_response',{p_response_id:id,p_status:'rejected'});if(error)throw error;setMessage('Response rejected.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not reject response.');}}

 if(loading)return <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading Phase 2.4 opportunity exchange…</div>;
 return <div className="space-y-7">
  <section><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="mt-1 text-3xl font-bold tracking-tight">Opportunity Exchange</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Buyer demand and property supply become actionable network opportunities. Brokers can search, match, respond and convert an accepted concrete match directly into a protected deal room.</p></div><button className={secondaryButton} onClick={()=>void load()}><RefreshCw className="size-4"/>Refresh</button></div></section>
  <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs leading-5 text-emerald-900"><b>Live shared feed:</b> new requirements and properties auto-publish here. Records beginning with <b>DEMO-</b> are example data, not real customers or owners.</div>
  {message&&<div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900">{message}</div>}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Open opportunities',posts.filter(p=>p.status==='open').length],['Buyer demands',posts.filter(p=>p.source_type==='requirement'&&p.status==='open').length],['Property supply',posts.filter(p=>p.source_type==='property'&&p.status==='open').length],['My responses',responses.filter(r=>r.broker_user_id===userId&&r.status==='active').length]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div></div>)}</section>

  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Search className="size-5 text-blue-600"/><h2 className="font-bold">Universal network search</h2></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_220px]"><input className={inputClass} placeholder="Search Raipur plot, Bhopal apartment, broker name, firm…" value={query} onChange={e=>setQuery(e.target.value)}/><select className={inputClass} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="all">All opportunities</option><option value="requirement">Buyer requirements</option><option value="property">Properties</option></select></div></section>

  <section className="grid gap-5 xl:grid-cols-[1.45fr_0.75fr]">
   <div className="space-y-4">{filtered.map(post=>{const req=post.requirement_id?reqMap.get(post.requirement_id):undefined;const prop=post.property_id?propertyMap.get(post.property_id):undefined;const own=post.posted_by_user_id===userId;const postResponses=responses.filter(r=>r.opportunity_id===post.id);const myResponse=postResponses.find(r=>r.broker_user_id===userId);let matches:{id:string;score:number;label:string}[]=[];if(req){matches=rankPropertyMatches(properties.map(p=>({id:p.id,type:p.property_type,area:[p.locality,p.city].filter(Boolean).join(', '),asking:Number(p.asking),size:Number(p.size),status:p.status})),{type:req.property_type,areas:[req.city],maxBudget:Number(req.max_budget),minSize:Number(req.min_size)}).slice(0,3).map(m=>{const p=propertyMap.get(m.propertyId)!;return{id:p.id,score:m.score,label:p.title};});}else if(prop){matches=requirements.map(r=>({r,m:scorePropertyMatch({id:prop.id,type:prop.property_type,area:[prop.locality,prop.city].filter(Boolean).join(', '),asking:Number(prop.asking),size:Number(prop.size),status:prop.status},{type:r.property_type,areas:[r.city],maxBudget:Number(r.max_budget),minSize:Number(r.min_size)})})).filter(x=>x.m.eligible).sort((a,b)=>b.m.score-a.m.score).slice(0,3).map(x=>({id:x.r.id,score:x.m.score,label:`${x.r.property_type} · ${x.r.city}`}));}const days=daysUntilExpiry(post.expires_at);return <article key={post.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${post.source_type==='requirement'?'bg-blue-50 text-blue-700':'bg-violet-50 text-violet-700'}`}>{post.source_type==='requirement'?'BUYER DEMAND':'PROPERTY SUPPLY'}</span><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${post.status==='open'?'bg-emerald-50 text-emerald-700':post.status==='matched'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{post.status}</span>{demoBadge(post.requirement_id||post.property_id)&&<span className="rounded-full bg-orange-50 px-2 py-1 text-[11px] font-bold text-orange-700">DEMO</span>}<span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold text-slate-600">{post.audience}</span></div><h3 className="mt-3 text-lg font-bold text-slate-950">{post.headline}</h3><div className="mt-1 text-xs text-slate-500">Posted by {profileLabel(profiles,post.posted_by_user_id)}</div></div><div className="text-right text-xs text-slate-500">{days!==null?<><Clock3 className="mr-1 inline size-3"/>{days<0?'Expired':`${days} day${days===1?'':'s'} left`}</>:null}</div></div>
    {req&&<div className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-3"><div><div className="text-[11px] uppercase text-slate-400">Location</div><b className="text-sm">{req.city}</b></div><div><div className="text-[11px] uppercase text-slate-400">Budget</div><b className="text-sm">{money(Number(req.max_budget))}</b></div><div><div className="text-[11px] uppercase text-slate-400">Minimum size</div><b className="text-sm">{Number(req.min_size).toLocaleString('en-IN')} sqft</b></div></div>}
    {prop&&<div className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-3"><div><div className="text-[11px] uppercase text-slate-400">Location</div><b className="text-sm">{prop.locality?`${prop.locality}, `:''}{prop.city}</b></div><div><div className="text-[11px] uppercase text-slate-400">Asking</div><b className="text-sm">{money(Number(prop.asking))}</b></div><div><div className="text-[11px] uppercase text-slate-400">Size</div><b className="text-sm">{Number(prop.size).toLocaleString('en-IN')} sqft</b></div></div>}
    {post.note&&<p className="mt-3 text-sm leading-6 text-slate-600">{post.note}</p>}
    <div className="mt-4 border-t border-slate-100 pt-4"><div className="flex items-center gap-2 text-xs font-bold text-slate-700"><Sparkles className="size-4 text-blue-600"/>Smart matches</div><div className="mt-2 grid gap-2">{matches.length?matches.map(m=><div key={m.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2"><div className="text-xs"><b>{m.label}</b><div className="text-slate-500">{m.id}</div></div><span className="text-xs font-bold text-emerald-700">{m.score}%</span></div>):<div className="text-xs text-slate-500">No eligible match in current shared inventory yet.</div>}</div></div>
    {own&&postResponses.length>0&&<div className="mt-4 rounded-xl border border-slate-200 p-3"><div className="text-xs font-bold">Responses</div><div className="mt-2 space-y-2">{postResponses.map(r=><div key={r.id} className="rounded-lg bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs"><b>{profileLabel(profiles,r.broker_user_id)}</b> · {r.response_type.replace('_',' ')} · {r.status}</div>{r.status==='active'&&r.response_type==='have_match'&&<div className="flex gap-2"><button className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-bold text-white" onClick={()=>void acceptResponse(r.id)}><CheckCircle2 className="size-3"/>Accept → Deal Room</button><button className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-bold" onClick={()=>void rejectResponse(r.id)}><XCircle className="size-3"/>Reject</button></div>}</div>{r.message&&<div className="mt-1 text-xs text-slate-600">{r.message}</div>}{(r.linked_property_id||r.linked_requirement_id)&&<div className="mt-1 text-[11px] text-blue-700">Linked: {r.linked_property_id||r.linked_requirement_id}</div>}</div>)}</div></div>}
    {!own&&post.status==='open'&&<ResponseComposer post={post} userId={userId} requirements={requirements} properties={properties} onSaved={load}/>} 
    {!own&&myResponse&&<div className="mt-2 text-xs text-slate-500">Your latest response: <b>{myResponse.response_type.replace('_',' ')}</b> · {myResponse.status}</div>}
    {own&&<OpportunitySettings post={post} profiles={profiles} recipients={recipients} onSaved={load}/>} 
   </article>;})}{!filtered.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">No opportunity matches this search.</div>}</div>

   <aside className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><UsersRound className="size-5 text-blue-600"/><h2 className="font-bold">Smart Broker Directory</h2></div><p className="mt-1 text-xs leading-5 text-slate-500">Filter by city and specialty; relevance also considers objective GENZ Trust Score.</p><div className="mt-4 grid gap-2"><input className={inputClass} placeholder="City e.g. Raipur" value={brokerCity} onChange={e=>setBrokerCity(e.target.value)}/><input className={inputClass} placeholder="Specialty e.g. Residential plot" value={brokerType} onChange={e=>setBrokerType(e.target.value)}/></div><div className="mt-4 space-y-3">{brokerRankings.slice(0,8).map(b=>{const p=profileMap.get(b.id)!;return <div key={b.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-2"><div><div className="flex items-center gap-1 text-sm font-bold">{p.verified&&<BadgeCheck className="size-4 text-blue-600"/>}{p.display_name}</div><div className="text-xs text-slate-500">{p.firm} · {p.broker_code}</div></div><div className="text-right"><div className="text-sm font-black text-blue-700">{b.score}</div><div className="text-[10px] uppercase text-slate-400">relevance</div></div></div><div className="mt-2 text-xs text-slate-600">Trust {b.trustScore}/100{Number(p.rating)>0?` · ${Number(p.rating).toFixed(1)}★`:''}</div><div className="mt-1 text-[11px] text-slate-500">{b.reasons.join(' · ')}</div>{(p.cities||[]).length>0&&<div className="mt-2 text-[11px] text-slate-500">Cities: {(p.cities||[]).join(', ')}</div>}{(p.specialties||[]).length>0&&<div className="text-[11px] text-slate-500">Specialties: {(p.specialties||[]).join(', ')}</div>}</div>;})}</div></div>
    <div className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="size-4 text-blue-400"/>Network rules</div><div className="mt-3 space-y-3 text-xs leading-5 text-slate-300"><p>Buyer phone and owner identity remain outside opportunity cards.</p><p>Only a concrete linked buyer/property match can be accepted into a Deal Room.</p><p>Selected/private audiences are enforced on opportunity records; the legacy Requirements/Properties modules still follow their existing member visibility rules during this beta.</p>{isAdmin&&<p className="text-blue-300">Admin view can review all opportunity records allowed by platform policy.</p>}</div></div>
   </aside>
  </section>
 </div>;
}
