'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { BadgeCheck, Building2, LockKeyhole, RefreshCw, Search, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';
import { getSupabaseNetworkClient } from '@/lib/supabase-network-client';

const inputClass='w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100';
const secondaryButton='inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50';
const money=(value:number|string)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value||0));

type PropertySupply={opportunity_id:string;property_id:string;headline:string;city:string;locality:string|null;property_type:string;size:number;mandate_status:string;posted_at:string;listing_broker_code:string;listing_broker_name:string;listing_broker_firm:string;listing_broker_verified:boolean;listing_broker_rating:number|string;listing_broker_review_count:number;listing_broker_account_status:string;my_match_count:number;best_match_score:number;share_grant_id:string|null;has_active_share:boolean;can_view_price:boolean;can_view_photos:boolean;can_view_videos:boolean;can_view_approx_location:boolean;can_view_exact_location:boolean;can_view_documents:boolean;can_view_owner_contact:boolean;allow_download:boolean;is_own_listing:boolean;};
type BuyerDemand={opportunity_id:string;requirement_id:string;headline:string;city:string;property_type:string;min_budget:number|string;max_budget:number|string;min_size:number;expires_at:string|null;posted_at:string;source_broker_code:string;source_broker_name:string;source_broker_firm:string;source_broker_verified:boolean;source_broker_rating:number|string;source_broker_review_count:number;source_broker_account_status:string;my_match_count:number;best_match_score:number;is_own_requirement:boolean;};

function Score({value,count}:{value:number;count:number}){const strong=value>=80,medium=value>=55;const cls=strong?'border-emerald-200 bg-emerald-50 text-emerald-800':medium?'border-amber-200 bg-amber-50 text-amber-800':'border-slate-200 bg-slate-50 text-slate-600';return <div className={`rounded-xl border px-3 py-2 text-xs font-semibold ${cls}`}><div>{value>0?`${value}% best match`:'No strong match yet'}</div><div className="mt-1 font-normal opacity-80">{count} compatible {count===1?'record':'records'} from your side</div></div>;}
function BrokerLine({code,name,firm,verified,rating,reviews,status}:{code:string;name:string;firm:string;verified:boolean;rating:number|string;reviews:number;status:string}){return <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-slate-600"><span className="font-semibold text-slate-800">{name}</span>{verified&&<BadgeCheck className="size-3.5 text-blue-600"/>}<span>· {firm}</span><span>· {code}</span><span>· ★ {Number(rating||0).toFixed(1)} ({reviews||0})</span>{status==='under_review'&&<span className="rounded-full bg-amber-100 px-2 py-0.5 font-semibold text-amber-800">Under review</span>}</div>;}
function budgetRange(item:BuyerDemand){const min=Number(item.min_budget||0);return min>0?`${money(min)} – ${money(item.max_budget)}`:`Up to ${money(item.max_budget)}`;}

export default function PrivacyDiscovery(){
  const supabase=useMemo(()=>getSupabaseNetworkClient(),[]);const [tab,setTab]=useState<'properties'|'buyers'>('properties');const [properties,setProperties]=useState<PropertySupply[]>([]);const [buyers,setBuyers]=useState<BuyerDemand[]>([]);const [query,setQuery]=useState('');const [city,setCity]=useState('');const [propertyType,setPropertyType]=useState('');const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');
  const load=useCallback(async()=>{setLoading(true);setMessage('');try{const [propertyRes,buyerRes]=await Promise.all([supabase.rpc('genz_discover_property_supply_v2',{p_query:query||null,p_city:city||null,p_property_type:propertyType||null,p_limit:100}),supabase.rpc('genz_discover_buyer_demand_v2',{p_query:query||null,p_city:city||null,p_property_type:propertyType||null,p_limit:100})]);if(propertyRes.error)throw propertyRes.error;if(buyerRes.error)throw buyerRes.error;setProperties((propertyRes.data||[]) as PropertySupply[]);setBuyers((buyerRes.data||[]) as BuyerDemand[]);}catch(error){setMessage(error instanceof Error?error.message:'Could not load privacy-safe discovery.');}finally{setLoading(false);}},[supabase,query,city,propertyType]);
  useEffect(()=>{void load();},[load]);
  const cityOptions=useMemo(()=>Array.from(new Set([...properties.map(x=>x.city),...buyers.map(x=>x.city)].filter(Boolean))).sort(),[properties,buyers]);const typeOptions=useMemo(()=>Array.from(new Set([...properties.map(x=>x.property_type),...buyers.map(x=>x.property_type)].filter(Boolean))).sort(),[properties,buyers]);

  return <div className="space-y-7">
    <section className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Discovery & Matching</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Find relevant property supply and buyer demand across GENZ without exposing protected price, exact GPS, owner contact, private documents or buyer identity.</p></div><button className={secondaryButton} onClick={()=>void load()} disabled={loading}><RefreshCw className={`size-4 ${loading?'animate-spin':''}`}/>Refresh</button></section>
    <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-xs leading-5 text-blue-900"><ShieldCheck className="mr-1 inline size-4"/><b>Privacy-safe by design:</b> property matching uses the buyer's full minimum–maximum budget range internally. Protected listing price itself is not returned here.</div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.5fr_1fr_1fr_auto]"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><input className={`${inputClass} pl-9`} placeholder="Search city, locality, type, Broker ID, firm…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className={inputClass} value={city} onChange={e=>setCity(e.target.value)}><option value="">All cities</option>{cityOptions.map(x=><option key={x} value={x}>{x}</option>)}</select><select className={inputClass} value={propertyType} onChange={e=>setPropertyType(e.target.value)}><option value="">All property types</option>{typeOptions.map(x=><option key={x} value={x}>{x}</option>)}</select><button className={secondaryButton} onClick={()=>void load()}><Search className="size-4"/>Search</button></div><div className="mt-4 flex gap-2"><button onClick={()=>setTab('properties')} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab==='properties'?'bg-slate-950 text-white':'bg-slate-100 text-slate-700'}`}>Property supply ({properties.length})</button><button onClick={()=>setTab('buyers')} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab==='buyers'?'bg-slate-950 text-white':'bg-slate-100 text-slate-700'}`}>Buyer demand ({buyers.length})</button></div></section>
    {message&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{message}</div>}{loading&&<div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Finding privacy-safe matches…</div>}
    {!loading&&tab==='properties'&&<section className="grid gap-4 xl:grid-cols-2">{properties.map(item=><article key={item.opportunity_id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><Building2 className="size-5 text-blue-600"/><h2 className="font-bold text-slate-950">{item.headline}</h2>{item.property_id.startsWith('DEMO-')&&<span className="rounded-full bg-violet-100 px-2 py-0.5 text-[10px] font-bold text-violet-700">DEMO</span>}</div><p className="mt-2 text-sm text-slate-600">{item.locality?`${item.locality}, `:''}{item.city} · {item.property_type} · {item.size} sqft</p></div><Score value={Number(item.best_match_score||0)} count={Number(item.my_match_count||0)}/></div><div className="mt-4"><BrokerLine code={item.listing_broker_code} name={item.listing_broker_name} firm={item.listing_broker_firm} verified={item.listing_broker_verified} rating={item.listing_broker_rating} reviews={item.listing_broker_review_count} status={item.listing_broker_account_status}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs"><div className="flex items-center gap-2 font-semibold text-slate-800"><LockKeyhole className="size-4"/>Price protected</div><p className="mt-1 text-slate-500">{item.can_view_price?'Permission granted — reveal through controlled sharing.':'Source broker has not released price.'}</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs"><div className="font-semibold text-slate-800">Access currently shared</div><p className="mt-1 text-slate-500">Photos {item.can_view_photos?'✓':'—'} · Videos {item.can_view_videos?'✓':'—'} · Exact pin {item.can_view_exact_location?'✓':'—'} · Docs {item.can_view_documents?'✓':'—'} · Owner contact {item.can_view_owner_contact?'✓':'—'}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Link href="/opportunities" className={secondaryButton}><Sparkles className="size-4"/>Open opportunity</Link>{item.has_active_share&&<Link href="/sharing" className={secondaryButton}><ShieldCheck className="size-4"/>Open shared access</Link>}{item.is_own_listing&&<span className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">Your listing</span>}</div></article>)}{properties.length===0&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500 xl:col-span-2">No property supply matches these filters.</div>}</section>}
    {!loading&&tab==='buyers'&&<section className="grid gap-4 xl:grid-cols-2">{buyers.map(item=><article key={item.opportunity_id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><UsersRound className="size-5 text-emerald-600"/><h2 className="font-bold text-slate-950">{item.headline}</h2>{item.requirement_id.startsWith('DEMO-')&&<span className="rounded-full bg-violet-100 px-2 py-0.5 text-[10px] font-bold text-violet-700">DEMO</span>}</div><p className="mt-2 text-sm text-slate-600">{item.city} · {item.property_type} · minimum {item.min_size} sqft · budget {budgetRange(item)}</p></div><Score value={Number(item.best_match_score||0)} count={Number(item.my_match_count||0)}/></div><div className="mt-4"><BrokerLine code={item.source_broker_code} name={item.source_broker_name} firm={item.source_broker_firm} verified={item.source_broker_verified} rating={item.source_broker_rating} reviews={item.source_broker_review_count} status={item.source_broker_account_status}/></div><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs leading-5 text-slate-600"><ShieldCheck className="mr-1 inline size-4"/><b>Buyer identity protected.</b> Name, phone and dedupe identity are not returned by discovery. Respond through the Opportunity Exchange so the source broker keeps control.</div><div className="mt-4 flex flex-wrap gap-2"><Link href="/opportunities" className={secondaryButton}><Sparkles className="size-4"/>Respond in Opportunity Exchange</Link>{item.is_own_requirement&&<span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Your requirement</span>}</div></article>)}{buyers.length===0&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500 xl:col-span-2">No buyer demand matches these filters.</div>}</section>}
  </div>;
}
