'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Gavel, RefreshCw, ShieldAlert } from 'lucide-react';
import { getSupabaseNetworkClient } from '@/lib/supabase-network-client';

type Row={broker_code:string;display_name:string;firm:string;account_status:'active'|'under_review'|'suspended'|'removed';public_status_note:string|null;status_effective_at:string;avatar_url:string|null};
type AppealRow={id:string;broker_code:string;display_name:string;firm:string;appealed_status:'suspended'|'removed';reason:string;status:'pending'|'accepted'|'rejected';admin_note:string|null;submitted_at:string;resolved_at:string|null};
const statuses=['active','under_review','suspended','removed'] as const;

export default function BrokerSafetyPage(){
 const supabase=useMemo(()=>getSupabaseNetworkClient(),[]);const [rows,setRows]=useState<Row[]>([]);const [appeals,setAppeals]=useState<AppealRow[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [busy,setBusy]=useState('');const [appealBusy,setAppealBusy]=useState('');
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{const {data:auth,error:authError}=await supabase.auth.getUser();if(authError)throw authError;if(!auth.user?.id)throw new Error('Sign in required.');const [{data,error},{data:appealData,error:appealError}]=await Promise.all([supabase.rpc('genz_admin_list_broker_public_statuses'),supabase.rpc('genz_admin_list_broker_status_appeals')]);if(error)throw error;if(appealError)throw appealError;setRows((data||[]) as Row[]);setAppeals((appealData||[]) as AppealRow[]);}catch(e){setRows([]);setAppeals([]);setMessage(e instanceof Error?e.message:'Could not load broker safety controls.');}finally{setLoading(false);}},[supabase]);
 useEffect(()=>{void load();},[load]);
 const update=async(row:Row,status:Row['account_status'],note:string)=>{setBusy(row.broker_code);setMessage('');try{const {error}=await supabase.rpc('genz_admin_set_broker_public_status',{p_broker_code:row.broker_code,p_status:status,p_public_note:note||null});if(error)throw error;setMessage(`${row.broker_code} status updated.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Status update failed.');}finally{setBusy('');}};
 const resolveAppeal=async(row:AppealRow,decision:'accepted'|'rejected',note:string)=>{setAppealBusy(row.id);setMessage('');try{const {error}=await supabase.rpc('genz_admin_resolve_broker_status_appeal',{p_appeal_id:row.id,p_decision:decision,p_admin_note:note||null});if(error)throw error;setMessage(decision==='accepted'?`${row.broker_code} appeal accepted and account restored to Active.`:`${row.broker_code} appeal rejected; public account status was not changed.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Appeal review failed.');}finally{setAppealBusy('');}};
 if(loading)return <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading broker safety controls…</div>;
 const pending=appeals.filter(item=>item.status==='pending');
 return <div className="space-y-8"><section><div className="text-xs font-bold uppercase tracking-[.18em] text-rose-600">Admin moderation</div><h1 className="mt-1 text-3xl font-black">Broker Safety</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Manage the status that appears on public Broker-ID verification pages. “Under review” must not be used as a public finding of fraud; publish concise factual notes only.</p></section>{message&&<div className="rounded-xl border border-slate-200 bg-white p-4 text-sm">{message}</div>}
 <section className="space-y-3"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-black">Public account status</h2><p className="mt-1 text-sm text-slate-500">Changes here are immediately visible on the public verification profile.</p></div></div>{!rows.length?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500"><ShieldAlert className="mx-auto mb-3 size-6"/>Admin access required, or no brokers are available.</div>:rows.map(row=><BrokerSafetyRow key={row.broker_code} row={row} busy={busy===row.broker_code} onSave={update}/>)}</section>
 <section className="space-y-3"><div><div className="flex items-center gap-2"><Gavel className="size-5 text-rose-600"/><h2 className="text-xl font-black">Status appeals</h2></div><p className="mt-1 text-sm text-slate-500">Private broker appeals for suspended or removed accounts. Accepting an appeal restores the account to Active and records an audit event.</p></div>{!appeals.length?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-7 text-sm text-slate-500">No broker status appeals yet.</div>:<div className="space-y-3">{appeals.map(row=><AppealCard key={row.id} row={row} busy={appealBusy===row.id} onResolve={resolveAppeal}/>)}</div>}{pending.length>0&&<div className="text-xs font-bold text-amber-700">{pending.length} appeal{pending.length===1?'':'s'} waiting for review.</div>}</section>
 <button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-black"><RefreshCw className="size-4"/>Refresh</button></div>;
}

function BrokerSafetyRow({row,busy,onSave}:{row:Row;busy:boolean;onSave:(row:Row,status:Row['account_status'],note:string)=>Promise<void>}){
 const [status,setStatus]=useState<Row['account_status']>(row.account_status);const [note,setNote]=useState(row.public_status_note||'');
 useEffect(()=>{setStatus(row.account_status);setNote(row.public_status_note||'');},[row]);
 return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 lg:grid-cols-[1fr_180px_1.2fr_auto] lg:items-end"><div><div className="font-black">{row.display_name}</div><div className="text-sm text-slate-500">{row.firm} · <span className="font-mono">{row.broker_code}</span></div><div className="mt-1 text-xs text-slate-400">Current since {new Date(row.status_effective_at).toLocaleString('en-IN')}</div></div><label className="text-xs font-bold text-slate-600">Public status<select value={status} onChange={e=>setStatus(e.target.value as Row['account_status'])} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm">{statuses.map(item=><option key={item} value={item}>{item.replace('_',' ')}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Public note<input value={note} onChange={e=>setNote(e.target.value.slice(0,500))} placeholder="Concise factual note" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><button disabled={busy} onClick={()=>void onSave(row,status,note)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy?'Saving…':'Save status'}</button></div></article>;
}

function AppealCard({row,busy,onResolve}:{row:AppealRow;busy:boolean;onResolve:(row:AppealRow,decision:'accepted'|'rejected',note:string)=>Promise<void>}){
 const [note,setNote]=useState(row.admin_note||'');
 useEffect(()=>setNote(row.admin_note||''),[row]);
 return <article className={`rounded-2xl border bg-white p-5 shadow-sm ${row.status==='pending'?'border-amber-200':'border-slate-200'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black">{row.display_name} · <span className="font-mono text-sm">{row.broker_code}</span></div><div className="mt-1 text-xs text-slate-500">Appealing <b className="capitalize">{row.appealed_status}</b> · submitted {new Date(row.submitted_at).toLocaleString('en-IN')}</div></div><span className={`rounded-full px-2.5 py-1 text-xs font-black capitalize ${row.status==='accepted'?'bg-emerald-50 text-emerald-700':row.status==='rejected'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}>{row.status}</span></div><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm whitespace-pre-wrap text-slate-700">{row.reason}</div>{row.status==='pending'?<div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto_auto] lg:items-end"><label className="text-xs font-bold text-slate-600">Private review note<textarea rows={3} value={note} onChange={e=>setNote(e.target.value.slice(0,2000))} placeholder="Optional note visible to this broker" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><button disabled={busy} onClick={()=>void onResolve(row,'accepted',note)} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy?'Working…':'Accept & restore Active'}</button><button disabled={busy} onClick={()=>void onResolve(row,'rejected',note)} className="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">Reject appeal</button></div>:<div className="mt-3 text-xs text-slate-500">Resolved {row.resolved_at?new Date(row.resolved_at).toLocaleString('en-IN'):'—'}{row.admin_note?` · Note: ${row.admin_note}`:''}</div>}</article>;
}
