"use client";
import {useState,type FormEvent} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {METHODS,agreement,calculateBrokerage,summarizeSettlement,type BrokerageTerms} from '@/lib/brokerage';
import {money,dateLabel,type DataRecord,type Member} from '@/lib/domain';
import {toast} from 'sonner';

type Intent={action:string;record?:DataRecord};
type Props={intent:Intent;records:DataRecord[];members:Member[];me:Member;onClose:()=>void;onSaved:(id?:string)=>Promise<void>};
const methodName=(method:string)=>METHODS.find(m=>m.value===method)?.label||'Fixed brokerage (legacy)';
function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <div className="field"><span>{label} *</span><Select value={value||undefined} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full h-11 bg-white"><SelectValue placeholder="Select"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
export function FinanceEditor({intent,records,members,me,onClose,onSaved}:Props){
 const r=intent.record,action=intent.action;const isNew=action==='deal',isAmend=action==='amendDeal',isDecision=action==='amendDecision',isClose=action==='closeDeal';
 const [v,setV]=useState<Record<string,any>>(()=>({...(r?.kind==='deal'?agreement(r.data):{method:'fixed',fixedAmount:'',percentage:'',ownerNet:'',listingShare:50,protectionDays:30,terms:'',feePayer:'Owner',dueDate:''}),propertyId:r?.kind==='property'?r.id:'',customerId:r?.kind==='customer'?r.id:'',finalPrice:r?.data.priceConfirmations?.[me.id]?.price||r?.data.finalPrice||'',consent:false,decision:'accepted',reason:'',note:''}));
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const set=(key:string,value:any)=>setV(p=>({...p,[key]:value}));
 const property=records.find(p=>p.id===v.propertyId),previewPrice=isClose?Number(v.finalPrice):Number(property?.data.asking||r?.data.asking||0);let preview:ReturnType<typeof calculateBrokerage>|null=null;try{preview=calculateBrokerage(isClose?agreement(r!.data):{...v,fixedAmount:Number(v.fixedAmount||0),percentage:Number(v.percentage||0),ownerNet:Number(v.ownerNet||0),listingShare:Number(v.listingShare)} as BrokerageTerms,previewPrice);}catch{}
 const field=(key:string,label:string,type='number',help?:string)=> <label className="field"><span>{label} *</span><input required type={type} value={v[key]??''} min={type==='number'?0:undefined} step={type==='number'?(key==='protectionDays'?'1':'0.01'):undefined} max={['listingShare','percentage'].includes(key)?100:undefined} onChange={e=>set(key,e.target.value)}/>{help?<small>{help}</small>:null}</label>;
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const body:any={...v,action,id:r?.kind==='deal'?r.id:undefined,expectedRevision:r?.revision,amendmentId:r?.data.pendingAmendment?.id};const res=await fetch('/api/network',{method:'POST',headers:{'Content-Type':'application/json','X-GenZ-Action':'1'},body:JSON.stringify(body)});const result:any=await res.json();if(!res.ok)throw new Error(result.error);toast.success(result.message||'Agreement record saved');await onSaved(result.id);onClose();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="modal-scroll sm:max-w-[760px]"><DialogHeader><DialogTitle>{isNew?'Agree on the brokerage formula':isAmend?'Propose a terms amendment':isDecision?'Review the proposed amendment':'Confirm the final selling price'}</DialogTitle><DialogDescription>{isNew?'Both brokers agree to one version of the calculation before the visit.':isAmend?'Current terms stay in force until the other broker accepts. Settlement verification pauses during review. Acceptance reopens closing; all past payments and confirmations are retained.':isDecision?'Read the proposed version. Only the other broker can accept or reject it.':'The server calculates brokerage from the locked agreement. Different prices put the settlement on hold; neither broker can close it alone.'}</DialogDescription></DialogHeader><form onSubmit={submit}><div className="form-grid">
 {isNew?<><Pick label="Verified property" value={v.propertyId} onChange={x=>set('propertyId',x)} options={records.filter(p=>p.kind==='property'&&p.status==='active').map(p=>({value:p.id,label:p.data.title}))}/><Pick label="Your buyer" value={v.customerId} onChange={x=>set('customerId',x)} options={records.filter(c=>c.kind==='customer'&&c.owner_id===me.id).map(c=>({value:c.id,label:c.data.name}))}/></>:null}
 {isNew||isAmend?<><Pick label="Brokerage method" value={v.method} onChange={x=>set('method',x)} options={METHODS}/>{v.method==='fixed'?field('fixedAmount','Fixed brokerage (₹)'):v.method==='percentage'?field('percentage','Brokerage rate (%)'):field('ownerNet','Proposed agreed owner net (₹)','number','Listing broker must confirm this matches the owner-approved mandate. This amount is shared with both deal participants.')}{field('listingShare','Listing broker share (%)')}{field('protectionDays','Proposed protection days','number','Protection begins on a manually acknowledged visit; this is not a network-wide cooling rule.')}<Pick label="Who owes the brokerage?" value={v.feePayer} onChange={x=>set('feePayer',x)} options={['Owner','Buyer','Owner and buyer (allocation in terms)'].map(x=>({value:x,label:x}))}/>{field('dueDate','Brokerage due date','date')}<label className="field wide"><span>Fee, protection and payment terms *</span><textarea required maxLength={2500} value={v.terms} onChange={e=>set('terms',e.target.value)}/><small>Specify who pays what. Amounts are contractual brokerage, before separately agreed taxes; no automatic GST/TDS treatment.</small></label>{isAmend?<label className="field wide"><span>Why is this amendment needed? *</span><textarea required value={v.reason} onChange={e=>set('reason',e.target.value)}/></label>:null}</>:null}
 {isClose?<>{field('finalPrice','Final declared selling price (₹)')}<label className="field wide"><span>Buyer / owner confirmation note *</span><textarea required maxLength={2500} value={v.note} onChange={e=>set('note',e.target.value)}/><small>Upload evidence for this agreement version before confirming. A statement by a broker is not independent owner verification.</small></label></>:null}
 {isDecision?<><div className="wide"><TermsRead terms={r!.data.pendingAmendment.terms}/><p className="note">Proposal reason: {r!.data.pendingAmendment.reason}</p></div><Pick label="Decision" value={v.decision} onChange={x=>set('decision',x)} options={[{value:'accepted',label:'Accept this amendment'},{value:'rejected',label:'Reject; keep current terms'}]}/><label className="field wide"><span>Review note *</span><textarea required value={v.reason} onChange={e=>set('reason',e.target.value)}/></label></>:null}
 {preview&&!isDecision?<div className={'note wide '+(preview.belowNet?'warn':'')}><b>{isClose?'Calculation at your proposed final price':'Illustration at current asking price'}: {money(previewPrice)}</b>{preview.belowNet?<p>Below owner net. Closing will be held—not silently treated as zero brokerage.</p>:<div className="record-details"><div><dt>Total brokerage</dt><dd>{money(preview.pool)}</dd></div><div><dt>Listing broker / buyer broker</dt><dd>{money(preview.listing)} / {money(preview.buyer)}</dd></div></div>}<small>{isClose?'Final entitlement requires matching confirmations.':'This is an estimate, not earned or paid commission.'}</small></div>:null}
 <label className="checkrow wide"><Checkbox checked={v.consent===true} onCheckedChange={x=>set('consent',x===true)}/><span>I confirm these terms / declarations and permission to record the necessary evidence.</span></label></div>{error?<p className="error-message" role="alert">{error}</p>:null}<div className="form-footer"><button type="button" className="secondary-btn" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Saving…':isClose?'Record my final price':isDecision?'Submit decision':'Submit agreement'}</button></div></form></DialogContent></Dialog>;
}
function TermsRead({terms:t}:{terms:BrokerageTerms}){return <><dl className="record-details"><div><dt>Method</dt><dd>{methodName(t.method)}</dd></div><div><dt>Calculation basis</dt><dd>{t.method==='fixed'?money(t.fixedAmount):t.method==='percentage'?t.percentage+'% of final selling price':'Final selling price − '+money(t.ownerNet)}</dd></div><div><dt>Listing / buyer split</dt><dd>{t.listingShare}% / {100-t.listingShare}%</dd></div><div><dt>Fee payer / due date</dt><dd>{t.feePayer} · {t.dueDate?dateLabel(t.dueDate):'Not recorded'}</dd></div><div className="full"><dt>Accepted terms</dt><dd style={{whiteSpace:'pre-wrap'}}>{t.terms}</dd></div></dl></>}
export function DealFinance({deal:r,payments,members,me,onFinance,onAction,onOpen}:{deal:DataRecord;payments:DataRecord[];members:Member[];me:Member;onFinance:(action:string)=>void;onAction:(action:string)=>void;onOpen:(id:string)=>void}){
 const d=r.data,t=agreement(d),summary=d.finance||summarizeSettlement(r,payments),name=(id:string)=>members.find(m=>m.id===id)?.name||'Broker',isParty=[r.owner_id,r.partner_id].includes(me.id);
 return <><a className="secondary-btn" href={'/documents?id='+r.id} target="_blank" rel="noreferrer">Print agreement record</a><p className="eyebrow" style={{marginTop:16}}>Agreement version {d.agreementVersion??0}{!d.agreement?' · Legacy fixed amount preserved':''}</p><TermsRead terms={t}/><div className="summary-line"><span>Buyer</span><b>{d.customerName}</b></div><div className="summary-line"><span>Final agreed selling price</span><b>{d.finalPrice?money(d.finalPrice):'Awaiting matching confirmations'}</b></div>
 {summary.holds.map((h:string)=><div className="note warn" key={h}>{h}</div>)}
 <div className="panel" style={{marginTop:20}}><div className="panel-head"><h3>{summary.provisional?'Estimated entitlement · not finalized':'Brokerage reconciliation'}</h3><b>{money(summary.pool)}</b></div><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Broker</TableHead><TableHead>Entitlement</TableHead><TableHead>Net received</TableHead><TableHead>Outstanding</TableHead><TableHead>Overpaid</TableHead></TableRow></TableHeader><TableBody>{Object.entries(summary.balances).map(([id,b]:[string,any])=><TableRow key={id}><TableCell>{name(id)}</TableCell><TableCell>{money(b.entitlement)}</TableCell><TableCell>{money(b.received)}</TableCell><TableCell>{money(b.outstanding)}</TableCell><TableCell>{money(b.overpaid)}</TableCell></TableRow>)}</TableBody></Table></div></div>
 <p className="tiny" style={{marginTop:10}}>Net received = allocated brokerage receipts + incoming co-broker transfers − outgoing transfers − linked refunds. Property consideration is excluded. {summary.provisional?'Estimates use asking price until both brokers confirm closing.':''}</p>
 {summary.overpaid?<p className="note warn">One or more brokers hold more than their entitlement. Record the agreed transfer or refund; past receipts are not rewritten.</p>:null}
 {t.dueDate&&summary.final&&t.dueDate<new Date().toISOString().slice(0,10)&&Object.values(summary.balances).some((b:any)=>b.outstanding>0)?<p className="note warn">Brokerage is overdue against the accepted due date.</p>:null}
 <div className="button-row" style={{marginTop:22}}>{r.status==='requested'&&r.partner_id===me.id?<button className="primary-btn" onClick={()=>onAction('dealDecision')}>Accept / decline terms</button>:null}{isParty&&['accepted','negotiation'].includes(r.status)&&!d.pendingAmendment?<><button className="primary-btn" onClick={()=>onAction('visit')}>Record visit</button><button className="secondary-btn" onClick={()=>onAction('offer')}>Add offer</button></>:null}{isParty&&['accepted','negotiation','closing','price_mismatch'].includes(r.status)&&!d.pendingAmendment?<button className="primary-btn" onClick={()=>onFinance('closeDeal')}>Confirm / revise my final price</button>:null}{isParty&&!['requested','declined'].includes(r.status)?<button className="secondary-btn" onClick={()=>onAction('payment')}>Record actual payment</button>:null}{isParty&&!['requested','declined'].includes(r.status)&&!d.pendingAmendment&&r.owner_id!==r.partner_id?<button className="secondary-btn" onClick={()=>onFinance('amendDeal')}>{r.status==='closed'?'Propose correction / reopen':'Propose terms amendment'}</button>:null}{isParty&&d.pendingAmendment&&d.pendingAmendment.proposedBy!==me.id?<button className="primary-btn" onClick={()=>onFinance('amendDecision')}>Review amendment</button>:null}{r.status==='closed'&&r.owner_id!==r.partner_id&&!d.pendingAmendment?<button className="secondary-btn" onClick={()=>onAction('review')}>Rate co-broker</button>:null}</div>
 {d.priceConfirmations?<section style={{marginTop:25}}><h3>Final price declarations</h3>{Object.entries(d.priceConfirmations).map(([id,x]:[string,any])=><div className="list-row" key={id}><div><b>{name(id)} · {money(x.price)}</b><p>{x.note}</p></div><span className="tiny">Agreement v{x.version} · {dateLabel(x.at)}</span></div>)}</section>:null}
 {d.pendingAmendment?<p className="note warn">Amendment v{d.pendingAmendment.version} proposed by {name(d.pendingAmendment.proposedBy)}. Existing terms are unchanged; settlement verification is paused.</p>:null}
 {d.amendmentHistory?.length?<section style={{marginTop:24}}><h3>Amendment history</h3>{d.amendmentHistory.map((a:any)=><details className="panel-body" key={a.id}><summary>Version {a.version} · {a.status} · {dateLabel(a.reviewedAt)}</summary>{a.previousAgreement?<><h4>Previous accepted terms · v{a.baseVersion}</h4><TermsRead terms={a.previousAgreement}/><h4>Replacement terms</h4></>:null}<TermsRead terms={a.terms}/><p className="muted">{a.reason} · {a.reviewNote}</p></details>)}</section>:null}
 {d.closingHistory?.length?<details style={{marginTop:24}}><summary className="text-link">Closing and correction history ({d.closingHistory.length})</summary>{d.closingHistory.map((h:any,i:number)=><div className="list-row" key={i}><p>{h.by?name(h.by):'Prior closing'} · {money(h.price??h.finalPrice??0)} · version {h.version}<br/>{h.note||h.reason}</p><span className="tiny">{h.result||'archived'} · {dateLabel(h.at||h.archivedAt)}</span></div>)}</details>:null}
 <h3 style={{marginTop:24}}>Offer history</h3>{d.offers?.length?d.offers.map((o:any)=><div className="list-row" key={o.id}><div><strong>{money(o.amount)}</strong><p>{o.note}</p></div><span className="tiny">{name(o.by)} · {dateLabel(o.at)}</span></div>):<p className="muted" style={{marginTop:10}}>No offers recorded.</p>}
 <h3 style={{marginTop:24}}>Actual payment records</h3>{payments.filter(p=>p.data.dealId===r.id).map(p=><button key={p.id} className="list-row w-full text-left" onClick={()=>onOpen(p.id)}><span>{money(p.data.amount)} · {p.data.mode}<p>{p.data.purpose}</p></span><span className="badge">{p.status.replaceAll('_',' ')}</span></button>)}
 <p className="note">Both brokers’ agreement does not replace the owner’s mandate or the buyer’s consent. Cash acknowledgment is not proof of legal compliance.</p></>;
}
