import type {DataRecord} from './domain';
export type BrokerageTerms={method:'fixed'|'percentage'|'above_net';fixedAmount:number;percentage:number;ownerNet:number;listingShare:number;protectionDays:number;terms:string;feePayer:string;dueDate:string};
export const METHODS=[{value:'fixed',label:'Fixed brokerage'},{value:'percentage',label:'Percentage of final price'},{value:'above_net',label:'Above owner-net'}];
export function agreement(data:Record<string,any>):BrokerageTerms{return data.agreement??{method:'fixed',fixedAmount:data.pool||0,percentage:0,ownerNet:0,listingShare:data.listingShare??50,protectionDays:data.protectionDays??30,terms:data.terms||'',feePayer:'Not recorded (legacy)',dueDate:''};}
const paise=(n:number)=>{if(!Number.isFinite(n)||n<0||n>100000000000)throw new Error('Invalid monetary amount');return BigInt(Math.round(n*100));};
const percent=(p:bigint,rate:number)=>{if(!Number.isFinite(rate)||rate<0||rate>100)throw new Error('Invalid percentage');return (p*BigInt(Math.round(rate*100))+5000n)/10000n;};
export function calculateBrokerage(t:BrokerageTerms,price:number){const sale=paise(price);const belowNet=t.method==='above_net'&&sale<paise(t.ownerNet);const total=t.method==='fixed'?paise(t.fixedAmount):t.method==='percentage'?percent(sale,t.percentage):belowNet?0n:sale-paise(t.ownerNet);const listing=percent(total,t.listingShare);return {pool:Number(total)/100,listing:Number(listing)/100,buyer:Number(total-listing)/100,belowNet};}
export function summarizeSettlement(deal:DataRecord,payments:DataRecord[]){
 const t=agreement(deal.data),price=deal.data.finalPrice??deal.data.asking??0,c=calculateBrokerage(t,price),parties=[...new Set([deal.owner_id,deal.partner_id].filter(Boolean) as string[])];
 const balances=Object.fromEntries(parties.map(id=>[id,{entitlement:(id===deal.owner_id?c.buyer:0)+(id===deal.partner_id?c.listing:0),received:0,outstanding:0,overpaid:0}]));
 const relevant=payments.filter(p=>p.data.dealId===deal.id),finalized=relevant.filter(p=>['verified','cash_acknowledged'].includes(p.status)),byId=new Map(relevant.map(p=>[p.id,p]));let collected=0,unallocated=0;
 const apply=(p:DataRecord,mult:number)=>{const d=p.data,amount=Math.round(Number(d.amount)*100)/100*mult;if(d.purpose==='Brokerage'){collected+=amount;if(balances[d.beneficiaryId])balances[d.beneficiaryId].received+=amount;else unallocated++;}else if(d.purpose==='Co-broker settlement'){if(balances[d.fromBrokerId]&&balances[d.toBrokerId]&&d.fromBrokerId!==d.toBrokerId){balances[d.fromBrokerId].received-=amount;balances[d.toBrokerId].received+=amount;}else unallocated++;}};
 for(const p of finalized){if(p.data.purpose==='Refund'){const original=byId.get(p.data.originalPaymentId);if(original&&['verified','cash_acknowledged'].includes(original.status)&&original.data.purpose!=='Refund')apply({...original,data:{...original.data,amount:p.data.amount}},-1);else unallocated++;}else apply(p,1);}
 for(const b of Object.values(balances)){b.received=Math.round(b.received*100)/100;b.outstanding=Math.round(Math.max(0,b.entitlement-b.received)*100)/100;b.overpaid=Math.round(Math.max(0,b.received-b.entitlement)*100)/100;}
 const holds:string[]=[];if(deal.data.pendingAmendment)holds.push('Amendment awaiting both-party agreement');if(deal.status==='price_mismatch')holds.push('Final price mismatch — settlement hold');if(c.belowNet)holds.push('Final price below agreed owner net');if(unallocated)holds.push('Legacy / unallocated payment records need reconciliation');if(relevant.some(p=>p.status==='disputed'))holds.push('Disputed payment');
 return {...c,price,balances,collected:Math.round(collected*100)/100,unallocated,holds,final:deal.status==='closed'&&!holds.length,provisional:deal.status!=='closed',overpaid:Object.values(balances).some(b=>b.overpaid>0)};
}
