import {requireMember,getRecord,isParty,fail,json,routeError,audit} from '@/lib/server';
import {agreement,calculateBrokerage} from '@/lib/brokerage';
import {money,dateLabel} from '@/lib/domain';
export const dynamic='force-dynamic';
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function GET(request:Request){try{const m=await requireMember(),id=new URL(request.url).searchParams.get('id');const r=await getRecord(id||'');if(!isParty(r,m))fail('Record access denied.',403);if(!['deal','payment'].includes(r.kind))fail('Printable record unavailable.');const d=r.data;let fields:any[];let title:string;
 if(r.kind==='deal'){const t=agreement(d),c=calculateBrokerage(t,d.finalPrice??d.asking);title='Co-broking agreement record';fields=[['Property',d.propertyTitle],['Buyer',d.customerName],['Agreement version',d.agreementVersion??'Legacy fixed'],['Method',t.method],['Fixed amount',t.method==='fixed'?money(t.fixedAmount):'Not applicable'],['Percentage',t.method==='percentage'?t.percentage+'%':'Not applicable'],['Owner net basis',t.method==='above_net'?money(t.ownerNet):'Not applicable'],['Final confirmed price',d.finalPrice?money(d.finalPrice):'Not finalized'],['Brokerage '+(d.finalPrice?'calculated':'estimate'),money(c.pool)],['Listing / buyer share',t.listingShare+'% / '+(100-t.listingShare)+'%'],['Fee payer',t.feePayer],['Due date',t.dueDate?dateLabel(t.dueDate):'Not recorded'],['Terms',t.terms],['Pending amendment',d.pendingAmendment?'Yes — settlement review hold':'No']];}
 else{if(!['verified','cash_acknowledged'].includes(r.status))fail('Only finalized payment records can produce an acknowledgment.');title=d.mode==='Cash'?'Cash acknowledgment record':'Verified payment record';fields=[['Amount',money(d.amount)],['Mode',d.mode],['Purpose',d.purpose],['Payer',d.payer],['Recipient',d.recipient],['Reference',d.reference||'Cash'],['Payment date',dateLabel(d.when)],['Review date',dateLabel(d.reviewedAt)],['Admin review note',d.reviewNote],['Agreement version when recorded',d.agreementVersion??'Legacy']];}
 await audit(m.id,'record.printed',r.id,title).run();return new Response('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>GENZ '+esc(title)+'</title><style>body{font:16px/1.6 Arial,sans-serif;color:#14243b;max-width:850px;margin:40px auto;padding:25px}h1{font-size:26px}table{width:100%;border-collapse:collapse}td{padding:12px;border-bottom:1px solid #ddd;vertical-align:top;white-space:pre-wrap}td:first-child{width:34%;color:#52637b}.note{background:#f0f4fa;padding:16px;font-size:14px}@media print{body{margin:0;padding:0}.print-help{display:none}}</style></head><body><p>GENZ · RAIPUR BROKER NETWORK</p><h1>'+esc(title)+'</h1><p>Status: '+esc(r.status)+'<br>Record: '+esc(r.id)+'</p><p class="print-help">Use your browser’s Print command to print or save as PDF.</p><table>'+fields.map(([k,v])=>'<tr><td>'+esc(k)+'</td><td>'+esc(v)+'</td></tr>').join('')+'</table><p class="note">This is an operational record of declarations and manual checks, not a tax invoice, certified eSign, title certificate, independent proof of cash delivery, or a guarantee of legal compliance. Accepted terms and original evidence remain controlling; estimates are not earned commission.</p></body></html>',{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'self'"}});}catch(e){return routeError(e);}}
